title: Coalition of Digital Engagements in Syracuse NY (CODES)
email: hi@codesyracuse.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codesyracuse
github_username:  codesyracuse

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - README.md
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
  - bin
  - docker-compose.yml
  - .gitignore
  - netlify_functions


