title: Coalition of Digital Engagement in Syracuse NY (CODES)
email: hi@codesyracuse.org
description: >- # this means to ignore newlines until "baseurl:"
  Through in-person engagements, local digital communities, and
  relationships with partner organizations, our mission is to educate
  individuals for digital careers. We will represent working
  professionals as well as any person who has a desire to join a
  digital profession.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codesyracuse
github_username:  codesyracuse

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss


# jekyll-seo-tag configuration
author: "CODES"
url: "codesyracuse.org"
title: "CODESyracuse"
description: "Coalition of Digital Engagement in Syracuse"
twitter:
  username: "codesyracuse"
  card: "Our mission is to educate individuals for digital careers."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - README.md
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
  - bin
  - docker-compose.yml
  - .gitignore


