version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.jekyll-cache
      - gem_cache:/gems
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_app/node_modules location. Thanks to PR from @brnluiz
      - notused:/usr/local/node_modules
      - notused2:/usr/local/jekyll-cache

    environment:
      - JEKYLL_ENV=development
volumes:
  gem_cache:
  notused:
  notused2:
